### PR TITLE
Final Project

### PR DESCRIPTION
**Pull request by ARJohansson**
This is my low-tech final. I haven't posted it to Azure yet, and I'm getting the pictures, but I think everything else is within the requirements.

Thanks for the review!

### CODE REVIEW

**Comment by StraussKE** [comment]
I've been sick since Tuesday, I'm so sorry!  I went to sleep after class and haven't been on my computer much since.  I'll look over this ASAP

**Comment by ARJohansson** [comment]
No worries! Let me know if you would like me to review your code, I still need to do a review, too.

**Comment by StraussKE** [comment]
hmm.  So I cloned it onto my machine, and it won't let me run it.  I got an exception when it tried to put the initial data into the database, so I opened powershell to generate the database and it won't let me.  Seems to not have the right commands for it or something?

I tried in both VS 2017 and VS 2019, neither worked.

**Comment by ARJohansson** [comment]
That's really weird... I'm running it in VS 2019 and it's been working fine... Does it have the migrations in it?

**Comment by StraussKE** [comment]
Yeah, it does.  So... Don't know why, but I ran into this last time I was trying to make things work in VS 2019. 

I included:<br/>
    DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.Dotnet" Version="2.0.0" <br/>
In the .csproj file and now it can access entity framework.

**Comment by StraussKE** [comment]
uhh... I'm sending you an email with what I just managed to do.  Got the database set up though...

**Comment by StraussKE** [comment]
# Code Review Form

|                                                      |                                                              |
| ---------------------------------------------------- | ------------------------------------------------------------ |
| Course  number, lab number and lab group             | Community Library                      |
| Developer                                            | Ashley Johansson                    |
| URL  for the project repository and branch on GitHub | https://github.com/ARJohansson/Community-Library/tree/Reporting |
| URL  on a server (if it has been published)          |                                                              |
| Reviewer  and Date                                   | Katie Strauss 3-15-2020                 |

###  Instructions

The reviewer will complete this form for the beta version of a lab assignment done by one of their lab partners. After filling out the “Beta” column and adding comments, the reviewer will submit this document to the Code Review assignment on the LMS.

The developer will revise the beta version of their lab work and fill out the “Production” column to reflect any changes they have made. The developer will submit this completed form along with the production version of their lab assignment.

### Review

| **Criteria**                                                 | **Beta** | **Release** |
| ------------------------------------------------------------ | -------- | ----------- |
| Does  it compile and run without errors?                     | Yes      |             |
| I found a few bugs, I emailed about them                                                    |          |             |
| Do all the pages load correctly?                             | Yes      |             |
|                                                              |          |             |
| Does  the style conform to MVC conventions and our class standards? | Yes      |             |
|                                                              |          |             |
| Do  all the links, buttons or other UI elements work correctly? | Yes      |             |
|                              |          |             |
| Do  the design and implementation conform to OOP best practices? | Yes      |             |
|                                                              |          |             |
| Does  the style conform to C# coding conventions?            | Yes      |             |
|                                                              |          |             |
| Does  the solution meet all the requirements? (list any issues below) | Yes      |             |
|                                                             |          |             |

#### Comments:
I love the idea, I love the site!  I wish you luck in finishing the rest of it, but the core components are great!
------

**Pull request merged**
